#!/stage1/busybox sh
export _PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys


# The buyer code is needed for the touch screen driver, so go ahead and
# copy all of the efs data now.
busybox mount -t yaffs2 /dev/block/mtdblock4 /efs
if busybox test -e /efs/buyer_code.dat ; then
	busybox cat /efs/buyer_code.dat > /sys/firmware/efs/buyer_code
fi
if busybox test -e /efs/imei/bt.txt ; then
	busybox cat /efs/imei/bt.txt > /sys/firmware/efs/bt_addr
fi
busybox umount /efs
busybox rm -rf /efs

/lvm/sbin/lvm vgscan --mknodes --ignorelockingfailure
/lvm/sbin/lvm vgchange -aly --ignorelockingfailure

busybox mount -t ext4 /dev/lvpool/system /system
busybox mount -t yaffs2 /dev/block/mtdblock3 /cache

image=/stage1/ramdisk.cpio

REC_BOOT_ADDR="0x57fff800"
REC_BOOT_MAGIC="0x5EC0B007" # Must be in caps.

if busybox grep -q bootmode=2 /proc/cmdline ; then
	# decoy recovery boot - clears bootmode and sets REC_BOOT_MAGIC
	bml_over_mtd dump recovery 102 reservoir 2004 /stage1/recovery.bin
	/stage1/kexec --load-hardboot --mem-min=0x50000000 /stage1/recovery.bin
	/system/bin/sync
	/stage1/kexec -e

elif ! busybox test -e /system/build.prop ; then
	# emergency boot
	erase_image cache
	busybox mkdir -p /cache
	busybox mount -t yaffs2 /dev/block/mtdblock3 /cache
	busybox mkdir /cache/recovery

	busybox mkdir -p /sdcard
	busybox mount -t vfat /dev/block/mmcblk0p1 /sdcard

	UPDATE=$(busybox cat /sdcard/cyanogenmod.cfg)

	if busybox test -n "$UPDATE" ; then
		busybox echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
	fi

	busybox devmem "$REC_BOOT_ADDR" 32 "REC_BOOT_MAGIC"
	image=/stage1/ramdisk-recovery.cpio

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting

elif busybox test `busybox devmem "$REC_BOOT_ADDR" 32` = "$REC_BOOT_MAGIC" ; then
	# recovery boot
	busybox devmem "$REC_BOOT_ADDR" 32 0x0
	image=/stage1/ramdisk-recovery.cpio

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

busybox umount /cache
busybox umount /system
busybox umount /sdcard
busybox rmdir /sdcard

busybox cpio -i < $image

if busybox grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	busybox cp lpm.rc init.rc
fi

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
